/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a4e152ab-8afa-40dd-b1c2-a2bc600c4d2f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_A5iFXw22Z",
    "aws_user_pools_web_client_id": "obrvcs0on5d6umk1034sam0g2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://s3ncd2spvbgfbi44eipebctt2m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-y7kxwc4y5ne77gkygprydysm2y",
    "aws_user_files_s3_bucket": "projectboards767a940442d14c169ca2466d147d866b584d1-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
